### ISSUE TITLE
Document usage with more wider examples

### ISSUE THREAD

**Issue by loveorigami** [creocoder/yii2-translateable#3]
В обсуждаемом нами на форуме расширении https://github.com/omgdef/yii2-multilingual-behavior
связь с полем перевода делалась так

``` php
$form->field($model, 'title_en')->textInput(['maxlength' => 512])
```

и данные сохранялись даже в отсутствии записей в таблице переводов (на случай, если таблица с записями на сайте уже есть).

Я у вас спрашивал, насчет составного языка
- Если запрашиваю

``` php
$form->field($model->translate('en-En'), 'title')->textInput(['maxlength' => 512])
```

Значение выводится. В таблице language - en-En
- translate('en') - не выводится.
- Если я дописываю поведение к уже существующей таблице с записями (articles) - новые записи в переводах не создаются.
- После сохранения - данные в таблицу перевода не записываются...

**Comment by creocoder** [comment]
@loveorigami Вы должны либо использовать полные id языков, либо сокращенные, но не всё вместе.

**Comment by creocoder** [comment]
@loveorigami Используйте везде сокращенные вариенты id, длинные варианты нужны только в очень сложных случаях, когда есть разница между переводом фразы к примеру в en-US и en-GB. Если у вас не такая ситуация, никогда не используйте полные варианты id, ни для базы, ни с расширением. В документации показаны примеры с полным вариантом id языка.

**Comment by creocoder** [comment]
> Если я дописываю поведение к уже существующей таблице с записями (articles) - новые записи в переводах не создаются.
> 
> После сохранения - данные в таблицу перевода не записываются...

Данные могут не сохраняться только в одном случае, это ошибки валидации модели `translationRelation`. Во всех остальных случаях всё должно сохраняться. Покрытие unit test-ами 100%, поэтому этот и многие другие случаи оттестированы.

**Comment by loveorigami** [comment]
Я не сомневаюсь, что работает и что все протестировано. 
Возможно, где-то закралась ошибка, т.к. в доке не написано, как привязать переводы к полю в форме и как их потом сохранить.
делаю так
- Создал миграцию, таблицу с переводами.
- Сгенерировал модель
- Подключил поведение.

``` php
$form->field($model, 'title')->textInput(['maxlength' => 512]) // русский
$form->field($model->translate('en'), 'title')->textInput(['maxlength' => 512]) // английский
```
- Захожу на редактор. Русский есть, т.к. это существующая запись.
- En нет - в таблице с переводами не создалось записей.
- Создаю запись вручную в PhpMyAdmin
- Захожу в редактор - в полях en данные отобразились.
- Сохраняю - данные не сохраняются.
- actionUpdate - стандартный

``` php
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //return $this->redirect(['update', 'id' => $model->id]);

            return $this->render('_form', [
                'model' => $model,
            ]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
```
- поиск по модели (закоменчено поведение от OmgDef/yii2-multilingual-behavior
  )

``` php
   protected function findModel($id)
    {

        if (is_array($id)) {
            //$model = Article::find()->multilingual()->andWhere(['id' => $id])->all();
            $model = Article::find()->with('translations')->andWhere(['id' => $id])->all();
        } else {
            //$model = Article::find()->multilingual()->andWhere(['id' => $id])->one();
            $model = Article::find()->with('translations')->andWhere(['id' => $id])->one();
        }

        if ($model !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
```
- В OmgDef/yii2-multilingual-behavior так работало. В контроллер ничего не надо было дописывать.
- К полям текст (En) у меня подключается FCkeditor
- Если я добавляю новый язык

``` php
$form->field($model->translate('de'), 'title')->textInput(['maxlength' => 512]) // немецкий
```

редактор слетает
![2015-01-30_11-36-28](https://cloud.githubusercontent.com/assets/98164/5972985/0334197c-a87c-11e4-851c-962581461ec3.jpg)
- Да и по лейблам не понятно - какой перевод нужно вводить в данное поле.
- В OmgDef/yii2-multilingual-behavior этот момент тоже учтен.

**Comment by creocoder** [comment]
Спасибо за фидбэк. Похоже настало время писать раздел `Advanced Usage` с подробными примерами как это использовать в рамках контроллеров и видов :) Конечно контроллеры должны как минимум заполнять модель c переводами данными из POST. В данном поведении нет никакой магии, оно не делает того, чего не просят (как все коробочные поведения). Автозаполнение моделей переводов данными в этом случае было бы злом, т.к. неизвестно что вы хотите делать с оригинальной моделью. Возможно какие то манипуляции без участия переводов. Я покажу в документации что нужно добавлять в контроллер. Вкратце тут стандартная ситуация на тему `dynamic/non-dynamic tabular data collection`. По желанию. Соответственно тут нужен код для этой ситуации в контроллере.

Про то как сделать различные label отдельно на каждый язык, также будет показано в документации.

**Comment by notgosu** [comment]
Присоединяюсь к запросу о детальной документации использования поведения при создании форм. Очень интересует вопрос работы поведения при создании форм через конструктор форм(в конфигах описана вся форма). Спасибо.

**Comment by creocoder** [comment]
@loveorigami, @notgosu Добавлены расширенные примеры в раздел `Advanced Usage`:

https://github.com/creocoder/yii2-translateable#advanced-usage

**Comment by Tivos** [comment]
Здравствуйте. 
подскажите как правильно соединить actionCreate()
в примере он такой:
public function actionCreate()
{
$model = new Post();

foreach (Yii::$app->request->post('PostTranslation', []) as $language => $data) {
foreach ($data as $attribute => $translation) {
$model->translate($language)->$attribute = $translation;
}
}

//...
}

у меня же после CRUD, он такой:
public function actionCreate()
{
$model = new Post();

if ($model->load(Yii::$app->request->post()) && $model->save()) {
return $this->redirect(['view', 'id' => $model->id]);
} else {
return $this->render('create', [
'model' => $model,
]);
}
}
