### ISSUE TITLE
Use of undefined constant OP_UPDATE - assumed 'OP_UPDATE'

### ISSUE THREAD

**Issue by tural-ali** [creocoder/yii2-translateable#4]
First of all I want to thank you for such and awesome database design suggestion. I remade whole application based on this structure.

But there is a little bug. 

Getting this error message while updating PostTranslation.

Use of undefined constant OP_UPDATE - assumed 'OP_UPDATE'

Made fix on Post model's following lines

```
public function transactions()
{
    return [
        self::SCENARIO_DEFAULT => self::OP_INSERT | OP_UPDATE,
    ];
}
```

to

```
public function transactions()
{
    return [
        self::SCENARIO_DEFAULT => self::'OP_INSERT' | 'OP_UPDATE'
    ];
}
```

It fixed.

Now, I'm curious if this problem was related only with quotes or it's something else?

**Comment by rokorolov** [comment]
Turalsprofile why not?

```
public function transactions()
{
    return [
        self::SCENARIO_DEFAULT => self::OP_INSERT | self::OP_UPDATE,
    ];
}
```

**Comment by tural-ali** [comment]
Please read question carefully. Whole question is related to this syntax issue:)

**Comment by creocoder** [comment]
@turalsprofile Good catch. I fixed README. Now it contains correct example.
